In [15]:
import pandas as pd

In [16]:
dfcust = pd.read_csv('dfcust_cleaned.csv').copy()
dfprop = pd.read_csv('dfprop_cleaned2.csv').copy()

In [17]:
dfcust.info()

<class 'pandas.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         162 non-null    int64
 1   customerid         162 non-null    str
 2   full_name          162 non-null    str
 3   age                162 non-null    int64
 4   entity             162 non-null    int64
 5   sex                162 non-null    str
 6   country            162 non-null    int64
 7   state              162 non-null    int64
 8   purpose            162 non-null    int64
 9   deal_satisfaction  162 non-null    int64
 10  mortgage           162 non-null    int64
 11  source             162 non-null    str
dtypes: int64(8), str(4)
memory usage: 15.3 KB

In [18]:
dfprop.info()

<class 'pandas.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  267 non-null    int64
 1   customerid  195 non-null    str
 2   id          267 non-null    int64
 3   building    267 non-null    int64
 4   date_sale   195 non-null    str
 5   type        267 non-null    str
 6   property#   267 non-null    int64
 7   area        267 non-null    float64
 8   price       267 non-null    str
 9   status      267 non-null    int64
dtypes: float64(1), int64(5), str(4)
memory usage: 21.0 KB

In [19]:
dfcust.columns = dfcust.columns.str.strip().str.replace('\ufeff', '')
dfprop.columns = dfprop.columns.str.strip().str.replace('\ufeff', '')

In [20]:
dfprop = dfprop.drop(columns = ['Unnamed: 0'])
dfprop.head()

,customerid,id,building,date_sale,type,property#,area,price,status
0,C0028,1030,1,2005-11-01,Apartment,30,743.09,"$246,172.68",1
1,C0027,1029,1,2005-10-01,Apartment,29,756.21,"$246,331.90",1
2,C0112,2002,2,2007-07-01,Apartment,2,587.28,"$209,280.91",1
3,C0160,2031,2,2007-12-01,Apartment,31,1604.75,"$452,667.01",1
4,C0014,1049,1,2004-11-01,Apartment,49,1375.45,"$467,083.31",1

In [21]:
dfcust = dfcust.drop(columns = ['Unnamed: 0'])
dfcust.head()

,customerid,full_name,age,entity,sex,country,state,purpose,deal_satisfaction,mortgage,source
0,C0110,Kareem Liu,57,1,F,1,1,1,4,1,Website
1,C0010,Trystan Oconnor,63,1,M,1,1,1,1,0,Website
2,C0132,Kale Gay,66,1,M,1,1,1,4,1,Agency
3,C0137,Russell Gross,66,1,M,1,1,1,5,0,Website
4,C0174,Marleez Co,62,0,Unknown,1,1,0,5,0,Website

In [22]:
dfprop['customerid'].to_list()

[' C0028 ',
 ' C0027 ',
 ' C0112 ',
 ' C0160 ',
 ' C0014 ',
 ' C0125 ',
 ' C0125 ',
 ' C0166 ',
 ' C0034 ',
 ' C0170 ',
 ' C0009 ',
 ' C0041 ',
 ' C0057 ',
 ' C0061 ',
 ' C0089 ',
 ' C0159 ',
 ' C0171 ',
 ' C0042 ',
 ' C0093 ',
 ' C0093 ',
 ' C0051 ',
 ' C0064 ',
 ' C0064 ',
 ' C0128 ',
 ' C0019 ',
 ' C0037 ',
 ' C0127 ',
 ' C0018 ',
 ' C0040 ',
 ' C0080 ',
 ' C0083 ',
 ' C0085 ',
 ' C0091 ',
 ' C0007 ',
 ' C0048 ',
 ' C0065 ',
 ' C0096 ',
 ' C0164 ',
 ' C0038 ',
 ' C0087 ',
 ' C0142 ',
 ' C0015 ',
 ' C0122 ',
 ' C0017 ',
 ' C0020 ',
 ' C0086 ',
 ' C0150 ',
 ' C0156 ',
 ' C0169 ',
 ' C0022 ',
 ' C0072 ',
 ' C0136 ',
 ' C0149 ',
 ' C0011 ',
 ' C0073 ',
 ' C0110 ',
 ' C0111 ',
 ' C0123 ',
 ' C0070 ',
 ' C0075 ',
 ' C0076 ',
 ' C0105 ',
 ' C0135 ',
 ' C0153 ',
 ' C0047 ',
 ' C0060 ',
 ' C0066 ',
 ' C0068 ',
 ' C0090 ',
 ' C0095 ',
 ' C0151 ',
 ' C0162 ',
 ' C0010 ',
 ' C0054 ',
 ' C0056 ',
 ' C0081 ',
 ' C0084 ',
 ' C0016 ',
 ' C0035 ',
 ' C0062 ',
 ' C0099 ',
 ' C0099 ',
 ' C0114 ',
 ' C0006 ',
 ' C0053 ',
 ' C0069 ',
 ' C0069 ',
 ' C0069 ',
 ' C0077 ',
 ' C0168 ',
 ' C0058 ',
 ' C0107 ',
 ' C0131 ',
 ' C0144 ',
 ' C0144 ',
 ' C0048 ',
 ' C0098 ',
 ' C0130 ',
 ' C0141 ',
 ' C0067 ',
 ' C0082 ',
 ' C0113 ',
 ' C0132 ',
 ' C0137 ',
 ' C0137 ',
 ' C0155 ',
 ' C0163 ',
 ' C0039 ',
 ' C0071 ',
 ' C0101 ',
 ' C0146 ',
 ' C0051 ',
 ' C0052 ',
 ' C0052 ',
 ' C0063 ',
 ' C0088 ',
 ' C0094 ',
 ' C0165 ',
 ' C0044 ',
 ' C0157 ',
 ' C0118 ',
 ' C0119 ',
 ' C0033 ',
 ' C0100 ',
 ' C0133 ',
 ' C0175 ',
 ' C0008 ',
 ' C0023 ',
 ' C0108 ',
 ' C0109 ',
 ' C0145 ',
 ' C0145 ',
 ' C0003 ',
 ' C0004 ',
 ' C0024 ',
 ' C0030 ',
 ' C0147 ',
 ' C0002 ',
 ' C0031 ',
 ' C0059 ',
 ' C0140 ',
 ' C0043 ',
 ' C0078 ',
 ' C0124 ',
 ' C0049 ',
 ' C0049 ',
 ' C0079 ',
 ' C0079 ',
 ' C0079 ',
 ' C0079 ',
 ' C0079 ',
 ' C0079 ',
 ' C0079 ',
 ' C0013 ',
 ' C0139 ',
 ' C0154 ',
 ' C0045 ',
 ' C0134 ',
 ' C0138 ',
 ' C0158 ',
 ' C0036 ',
 ' C0074 ',
 ' C0120 ',
 ' C0120 ',
 ' C0005 ',
 ' C0032 ',
 ' C0126 ',
 ' C0106 ',
 ' C0115 ',
 ' C0115 ',
 ' C0129 ',
 ' C0129 ',
 ' C0103 ',
 ' C0103 ',
 ' C0021 ',
 ' C0148 ',
 ' C0172 ',
 ' C0104 ',
 nan,
 ' C0001 ',
 ' C0012 ',
 ' C0012 ',
 ' C0025 ',
 ' C0029 ',
 ' C0029 ',
 ' C0055 ',
 ' C0121 ',
 ' C0174 ',
 ' C0174 ',
 ' C0174 ',
 ' C0174 ',
 ' C0174 ',
 ' C0174 ',
 ' C0174 ',
 ' C0174 ',
 ' C0174 ',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan]

In [23]:
dfprop['customerid'] = dfprop['customerid'].str.strip()

In [24]:
dfmerged = dfcust.merge(dfprop, how = 'outer', on = 'customerid')

In [25]:
dfmerged['customerid'].duplicated().sum()

np.int64(104)

In [26]:
dfmerged.info()

<class 'pandas.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customerid         195 non-null    str
 1   full_name          195 non-null    str
 2   age                195 non-null    float64
 3   entity             195 non-null    float64
 4   sex                195 non-null    str
 5   country            195 non-null    float64
 6   state              195 non-null    float64
 7   purpose            195 non-null    float64
 8   deal_satisfaction  195 non-null    float64
 9   mortgage           195 non-null    float64
 10  source             195 non-null    str
 11  id                 267 non-null    int64
 12  building           267 non-null    int64
 13  date_sale          195 non-null    str
 14  type               267 non-null    str
 15  property#          267 non-null    int64
 16  area               267 non-null    float64
 17  price              267 non-null    str
 18  status             267 non-null    int64
dtypes: float64(8), int64(4), str(7)
memory usage: 39.8 KB

In [27]:
dfmerged.tail()

,customerid,full_name,age,entity,sex,country,state,purpose,deal_satisfaction,mortgage,source,id,building,date_sale,type,property#,area,price,status
262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5044,5,NaN,Apartment,44,1238.58,"$322,610.74",0
263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5047,5,NaN,Apartment,47,794.52,"$279,191.26",0
264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5048,5,NaN,Apartment,48,1013.27,"$287,996.53",0
265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5050,5,NaN,Apartment,50,1074.71,"$365,868.78",0
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5051,5,NaN,Apartment,51,789.25,"$199,216.40",0

In [28]:
dfmerged.to_csv('real-state-data.csv')